/**
 * Shared guardrails — imported by every prompt-builder module under
 * `lib/prompts/`. Tuning a kid-safe / anatomy / KDP-quality rule once here
 * propagates to every page, cover, and reference-led prompt.
 *
 * NOTE: these strings are sent to image / text models verbatim. Read the
 * "Prompts" section of AGENTS.md before editing — example sub-clauses leak
 * into output (the savanna / acacia / coral examples that used to live in
 * this file primed Gemini to draw trees on every book).
 */

// IP / brand-avoidance rule shared by every prompt-builder that asks an LLM
// to invent characters, scenes, or page subjects. Keeps the wording in one
// place so adding "no Marvel" once propagates to chat planning, story
// planning, single-image-ideas, and the JSON book planner. Re-exported via
// `lib/prompts/index.ts` because `lib/book-chat.ts` and `lib/book-planner.ts`
// import it from outside the `lib/prompts/` folder.
export const NO_REAL_BRAND_RULE =
  "Avoid copyrighted material — no Disney / Pixar / Marvel characters, no Pokémon, no branded logos, no real celebrities.";

export const ANATOMY_GUARDRAIL =
  "Anatomy must be correct and natural-looking: exactly the right number of legs, arms, ears, eyes, tail, fingers, and wings for the species — symmetrical facial features, both eyes on the face, mouth properly placed — nothing duplicated, nothing fused, nothing misaligned, nothing out of place. No extra limbs, no missing limbs.";

// Vehicles, objects, and inanimate things drawn with cartoon faces (talking
// trucks, friendly suns, character clouds) are a recurring trouble spot —
// the model often produces uneven eyes, off-center mouth, or "smudged"
// facial features. This guardrail enforces a clean, simple cartoon-face
// pattern wherever a non-living subject has a face.
export const ANTHRO_FACE_GUARDRAIL =
  "If the subject is an inanimate object that has been given a cartoon face — applies whenever the subject is a non-creature thing such as a vehicle, fruit, sun, cloud, household item, or similar — the face MUST be SIMPLE and SYMMETRIC: exactly TWO equal-sized round eyes (filled black or simple circle outline), placed at the same height, evenly spaced left-and-right around the centerline, never cross-eyed and never with iris pupils that wander. ONE clearly visible mouth (a simple curved smile or open round 'O'), centered horizontally below the eyes. No eyebrows, no complex mouth shapes, no teeth detail, no crooked features. The face must look intentional and clean — like a child-friendly cartoon decal, not a smudged or distorted attempt. When the subject is a vehicle, place the face on the front grille / windshield area, not on the side.";

export const ARTIFACT_GUARDRAIL =
  "ABSOLUTELY NO TEXT OR ATTRIBUTION OF ANY KIND ANYWHERE on the page. This includes: no model name (NO 'Nano', 'Banana', 'Gemini', 'AI', 'Generated by', or any vendor/product attribution text — the model must NEVER stamp its own name on the image), no letters, no numbers, no labels, no speech bubbles, no watermarks (visible or stylized), no signatures, no logos, no captions, no frames-within-frames, no page numbers, no signature dots, no glassy/translucent text overlays in any corner. Scan the four corners and bottom strip of the canvas for stray attribution text and ensure they are completely empty of letters. A single coherent illustration with ZERO text marks.";

// KDP print-ready quality directives — applied to every page.
export const KDP_QUALITY_GUARDRAIL =
  "KDP print-ready quality: 100% pure black ink lines on 100% pure white page background. No solid black fills anywhere on the page — not on the subject's body parts (no all-black paw, leg, mane, tail), not on the sky, not on the ground, not on any prop. No gray shading, no halftones, no hatching, no stippling, no cross-hatch, no near-black tones, no near-white tones. No gradients of any kind: no atmospheric gradient near the page edges, no soft gray haze under the subject, no shadow gradient on the ground, no vignette around the artwork, no gray fog at the bottom or sides. The space between the printer's outer rectangle and the artwork is PURE WHITE — never a faded or grayish tint. The ground is rendered as a single thin line plus optional small detail (grass tufts / sand dots / floor lines), never as a shaded gray area. No silhouette / negative-space drawing (the page is never an inverted dark scene with white outlines — black is the line color, white is the background, always). Every line is a closed crisp continuous stroke — no broken lines, no gaps, no double lines. All shapes are fully enclosed by their outlines so a child can color them in cleanly without color spilling out. Consistent thick uniform line weight throughout the page (~3pt at print size). High-resolution, vector-clean appearance.";

// CRITICAL — repeat the color rule with absolute clarity at the END of the
// prompt. Scene/subject text often mentions colors ("golden grasses", "blue
// sky", "green trees", "brown fox") for identification — Gemini occasionally
// interprets those as fill instructions and emits a partly-colored image.
// This override is the LAST thing the model reads.
export const FINAL_BW_OVERRIDE =
  "🚫 ABSOLUTE COLOR OVERRIDE — READ THIS LAST: This image MUST be 100% pure black-and-white line art ONLY. Even though the subject and scene descriptions above mention colors (golden, blue, green, brown, red, pink, yellow, orange, etc.), those color words are for IDENTIFICATION ONLY — they describe what the subject IS in real life, NOT what to paint. The actual generated image contains ZERO color, ZERO shading, ZERO gray fills, ZERO gradients. Pure white background, pure black outlines. If you are about to add any color or any non-black non-white pixel anywhere — STOP and remove it. The output is a coloring page for a child to color in themselves.";

export const STYLE_CONSISTENCY =
  "Maintain a consistent cartoon style across the whole book: same line weight, same eye style (round friendly), same proportions philosophy, same level of detail. This page must look like a sibling of the other pages in the same book.";

// IMPORTANT: the scene should EXTEND to all four edges of the canvas like
// a real printed coloring-book page (think: cow standing in a field with
// barn + sky reaching every edge; pig in a meadow with trees + sun + fence
// reaching every edge). NO empty white margin around the scene. Only
// PRINTER-SAFE detail rule: keep critical features (eyes, mouth, faces,
// small text-like elements) at least 4% away from the absolute edge so a
// 2% trim variance during binding doesn't crop them off — but background
// elements (grass, sky, hills, water, foliage) SHOULD reach the page edge.
export const FILL_CANVAS_RULE =
  "FILL THE ENTIRE CANVAS EDGE-TO-EDGE: the illustration extends to all four edges of the page like a printed picture-book scene. Whatever supporting elements belong to the subject's environment fill the canvas to the edges. Do not leave empty white margin around the artwork; do not contract the scene into the center with white space around it. Printer-safety: keep critical detail (the main character's face, eyes, mouth, tiny features) at least 4% away from the absolute edge so a binding-trim variance doesn't crop them off. Background elements MUST reach all the way to the page edge — pick whichever elements fit the subject's environment, never default to grass / hills / tree branches / clouds unless the subject lives in that kind of setting.";

// Used by the "minimal" / "framed" presets where the subject sits on
// mostly-white (not an edge-to-edge scene). Keeps essential features
// inside a generous central area without forcing background to the edges
// (since there isn't one).
export const PRINT_TRIM_SAFETY_RULE =
  "PRINTER TRIM SAFETY: Keep the subject's critical features (face, eyes, hands, paws, tail tip) at least 5% inside from every edge of the page so a small binding-trim variance doesn't crop them. The subject silhouette should not bump directly into the page edge.";

// SINGLE source of truth for the printed page outline. Compressed to one
// concise rule on purpose — earlier versions repeated "border" 13+ times
// in one paragraph and the model started drawing two of them. KDP-framed:
// the inset and trim safety align with KDP's printer-safe interior spec.
export const DRAW_BORDER_RULE =
  "📐 PAGE FRAME (KDP printer-safe rule, applies once — DO NOT REPEAT): Draw exactly ONE thin solid black rectangular outline at 3% inset from each page edge. Line weight ~1.5px, uniform thickness, four 90° corners, plain rectangle only. NO ornaments, NO rounded corners, NO decorative flourishes, NO double lines, NO second inset rectangle inside the first — if you start to draw a second one, stop. Keep all artwork inside this outline with ~4% buffer; nothing touches or crosses it. Identical position and thickness on every page in the book.";

// Locks the LOOK of common scene elements when (and only when) they actually
// belong in the scene. Critically does NOT mandate that they appear — only
// describes how to draw them IF the scene calls for them. Without this
// "IF/ONLY" framing, Gemini was adding sun+clouds to every page including
// underwater, indoor, space, and night scenes.
export const COMMON_ELEMENT_STYLE =
  "STYLE LOCK FOR COMMON ELEMENTS — IMPORTANT: Do NOT add scene elements that are not explicitly listed in the scene description above. Do not invent a sun, sky, clouds, ground, trees, road, or any other backdrop element if the scene description does not call for them. If the scene is underwater → no sun/clouds, draw water and seabed instead. If indoor → no sun/clouds, draw walls/floor instead. If space/night → no sun, draw stars/moon. ⚠️ NEVER draw BOTH a sun AND a moon in the same scene — they cannot coexist. Day scene = sun only (no moon, no stars). Night scene = moon and/or stars only (no sun). If the scene description doesn't specify time of day, default to DAY (sun, no moon). ONLY IF the scene description explicitly mentions these elements, render them as: SUN = a plain simple circle with exactly 8 short straight evenly-spaced rays, NO face, NO smile, NO eyes; CLOUDS = simple rounded bumpy outlined shapes with no detail inside; GROUND = a single short horizontal line with at most 2 small grass tufts; TREES = simple rounded bushy crown on a straight trunk; ROAD = two parallel straight lines. Never decorate these supporting elements with faces or expressions — they are background only.";

export const KID_SAFE_CONTENT_RULE =
  "Kid-safe: every creature, plant, and object is a round, smiling, friendly cartoon — would pass a parent's bedtime test for a 4-year-old. No realistic-anatomy detail on any object (no organ-like shapes, vein/intestine textures, brain-coral lookalikes); no skulls, bones, blood, scars, fangs, snarls, hunting scenes; no weapons of any kind (replace swords/guns with flags, shields, treasure); no fire/destruction, dead trees with face-like knots, hollow or glowing eyes; no medical/dental/surgical imagery, graveyards, frightening ghosts/demons; no religious or political symbols (crosses, swastikas, national flags); no alcohol/cigarettes/drugs; nothing sexual or suggestive. When a brief implies any of the above, swap to a kid-safe alternative (shark teeth → closed smile, sword → flag, cracked tree → healthy tree).";

// Five load-bearing rules stated once. Repetition was actively hurting
// compliance — the prior version mentioned "draw one border" 3-4 times
// and the model started drawing two nested borders.
export const ANCHOR =
  "Five rules to obey: " +
  "(1) Pure black-and-white LINE ART only — thin black outlines on a 100% white page. " +
  "    No solid black fills (a paw, leg, body, hair, sky, or any other region must NEVER be filled solid black). " +
  "    No gray shading, no halftones, no hatching, no stippling, no cross-hatch, no spot-blacks, no silhouettes. " +
  "    No white-on-black inversion (the page is NEVER a black sky / black background with white drawings — even for night, space, or outer-space scenes the rule is reversed: draw black outlines of stars, moon, planets on the white page, NOT a black background with white stars). " +
  "    Color words in the brief refer to the subject's identity (a 'black cat', a 'red barn'), never to actual ink — render them as outlines only, the kid colors them. " +
  "(2) The scene fills the canvas edge-to-edge — no empty white margin around the artwork. " +
  "(3) The single main subject is 50-65% of the page (large, dominant, same scale on every page); the rest of the canvas is themed background, not white space. " +
  "(4) Each named character appears exactly once per page. Crowds are simple small silhouettes without detailed faces — never repeat the hero. " +
  "(5) Only the named subject is drawn as a character. No partial creatures (tails, ears, paws, manes) peeking from the background — the background is environment only.";
